### ISSUE TITLE
Is there a "get_lldp_neighbors" api call?

### ISSUE THREAD

**Issue by PeiwenChen** [Juniper/net-netconf#48]
@jeremyschulman 
Hi, 

I need to get the LLDP neighbors info.
But found out there is no LLDP info in the https://github.com/Juniper/ruby-junos-ez-stdlib.
Do you have any apis for LLDP neighbors info?

If not, then I have to send show command and then parse the returned xml info?

Thanks a lot!
Peiwen

**Comment by dgjnpr** [comment]
Hi @PeiwenChen,

There is no LLDP neighbor gathering API in this repo. For now you will need to use the get_lldp_neighbors_information NETCONF RPC.
