### ISSUE TITLE
The netconf RPC call "get_ethernet_switching_table_information" is not avaliable

### ISSUE THREAD

**Issue by PeiwenChen** [Juniper/net-netconf#49]
```
peiwen@chi-mgmtsw-hy094-1> show ethernet-switching table |display xml rpc 
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/12.3R9/junos">
    <rpc>
        <get-ethernet-switching-table-information>
        </get-ethernet-switching-table-information>
    </rpc>
    <cli>
        <banner>{master:0}</banner>
    </cli>
</rpc-reply>

{master:0}
```

According to the above, I am trying to call this, but it did not work.
`table = netconf_rpc.get_ethernet_switching_table_information
`

And I tried this, it did not work neither.
`table = netconf_rpc.get_ethernet-switching_table_information
`
@dgjnpr 
Can you point to me the correct RPC call for this command?

**Comment by ganeshnalawade** [comment]
@PeiwenChen What is the error message you are seeing?
I tried below code snippet and it is works for me.
```
require 'net/netconf'

login = { :target => 'xxxx', :username => "xxx", :password => "xxx" }

Netconf::SSH.new( login ){ |dev|  
  et = dev.rpc.get_ethernet_switching_table_information
  puts et 
}
```

**Comment by PeiwenChen** [comment]
@ganeshnalawade 

This thing is this RPC call is not available on MX80.
Do you try on MX80?

**Comment by dgjnpr** [comment]
assuming this is resolved as no follow up
